defaults: ../../../nemo_gym/gdpo_example_tool_call_multireward.yaml
grpo:
  num_prompts_per_step: 8
  num_generations_per_prompt: 8
policy:
  model_name: Qwen/Qwen2.5-1.5B-Instruct
  max_total_sequence_length: 2048
  dtensor_cfg:
    enabled: true
    tensor_parallel_size: 1
  megatron_cfg:
    _override_: true
    enabled: false
  optimizer:
    name: torch.optim.AdamW
    kwargs:
      lr: 5.0e-06
      weight_decay: 0.01
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
  generation:
    vllm_cfg:
      http_server_serving_chat_kwargs:
        tool_parser: hermes
checkpointing:
  checkpoint_dir: results/gdpo-qwen2.5-1.5b-1n8g-fsdp2tp1-gym-multireward
logger:
  wandb:
    project: nemo-rl
    name: gdpo-qwen2.5-1.5b-1n8g-fsdp2tp1-gym-multireward
