defaults: ./grpo-dapomath17k-dsv3-32n8g-megatron.yaml
policy:
  megatron_cfg:
    tensor_model_parallel_size: 4
    expert_model_parallel_size: 16
    # DeepEP is supported for Ampere, Hopper, and Blackwell (B200/B300) GPUs
    moe_enable_deepep: false
    moe_token_dispatcher_type: "alltoall"
checkpointing:
  checkpoint_dir: results/grpo-dapomath17k-dsv3-32n4g-megatron
logger:
  wandb:
    name: grpo-dapomath17k-dsv3-32n4g-megatron
  mlflow:
    run_name: grpo-dapomath17k-dsv3-32n4g-megatron
cluster:
  gpus_per_node: 4

